name = "PhysiCellCellCreator"
uuid = "eac91067-0c6e-4a29-b848-3b4e7cf67017"
authors = ["Daniel Bergman <danielrbergman@gmail.com> and contributors"]
version = "0.0.5"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.0"
LightXML = "0.9.1"
LinearAlgebra = "1.10.8 - 1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
